name: tests unitaires
on: [push]
jobs:
 test1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python for Demo
      uses: actions/setup-python@v4
    - name: Install pytest
      run: pip install pytest
    - name: Run tests
      run: pytest TP1/test.py
    - run: echo "1:${{ github.ref }}"
    - run: echo "repo1:${{ github.repository }}."
